[package]
name = "network_time_simulator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simulator"
path = "src/simulator/leader.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork = "0.1.22"
nix = "0.26.2"
posixmq = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
rand = {version = "0.8.5", features = ["small_rng"] }
serial = "0.4.0"
serial_test = "3.0.0"
arr_macro = "0.2.1"
toml = "0.8.14"
ntest = "0.9.3"
gml_parser = "0.1.1"
libc = "0.2.162"
netns-rs = "0.1.0"
rtnetlink = "0.14.1"
#rtnetlink = {git = "https://github.com/Lix0u/rtnetlink.git", branch = "release-14.1"}
futures = "0.3.31"
netlink-packet-route = "0.19.0"
tokio = {version = "1", features = ["full"]}
test-log = "0.2.16"

[profile.dev]
panic = "abort"
overflow-checks = false
opt-level = "s"
lto = true
codegen-units = 1

[profile.release]
panic = "abort"
overflow-checks = false
opt-level = "s"
lto = true
codegen-units = 1
