# Queue name
qname = 'some_queue'

# Random 10
random_10 = 123

#logs
logs = ["trace", "debug", "warn", "info", "message"]
log_file = "log.txt"

# 10 of followers
nb_follower = 4

# Graph
graph = '3_clients_1_server.gml'

# Executables
[executables]
[[executables.exe]]
name = 'client1'
path = 'client'
args = ["./client", "-i", "10.0.0.4", "-p", "4443", "-o", "10", "-I", "1"]
node_ids = [1]


[[executables.exe]]
name = 'client2'
path = 'client'
args = ["./client", "-i", "10.0.0.4", "-p", "4443", "-o", "10", "-I", "2"]
node_ids = [2]


[[executables.exe]]
name = 'client3'
path = 'client'
args = ["./client", "-i", "10.0.0.4", "-p", "4443", "-o", "10", "-I", "3"]
node_ids = [3]


[[executables.exe]]
name = 'server'
path = 'server_multi'
args = ["./server_multi", "-i", "10.0.0.4", "-p", "4443", "-o", "10", "-c", "3"]
node_ids = [4]


